server:
  address: 0.0.0.0
  servlet:
    contextPath: /budget
  port: 8443

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

categories:
  rules:
    - keyword: "S/ LEVANTAMENTOS"
      category: Bank
      sub-category: Fees
    - keyword: "VODAFONE"
      category: Utilities
      sub-category: Internet
    - keyword: "BALTAREJO"
      category: Daily_Livings
      sub-category: Gym
    - keyword: "IDEIAS DECIMAIS"
      category: House_Construction
      sub-category: Contractor
    - keyword: "COMISSÃO TRANSFERÊNCIA"
      category: Bank
      sub-category: Fees
    - keyword: "AGUAS VALONGO"
      category: Utilities
      sub-category: Water
    - keyword: "IMP.  SELO"
      category: Bank
      sub-category: Fees
    - keyword: "UBER    EATS"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "UBER  EATS"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "COMPRA AUTO REP MOU"
      category: Utilities
      sub-category: Gas
    - keyword: "COMPRA BURGER KING"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "COMPRA CHURRASQ"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "COMPRA CONTINENTE"
      category: Home
      sub-category: Groceries
    - keyword: "COMPRA DISTRICOURA"
      category: Home
      sub-category: Groceries
    - keyword: "COMPRA INTERMARCHE"
      category: Home
      sub-category: Groceries
    - keyword: "COMPRA INTERVALONGO"
      category: Home
      sub-category: Groceries
    - keyword: "COMPRA KFC"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "COMPRA MCD"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "COMPRA PINGO DOCE"
      category: Home
      sub-category: Groceries
    - keyword: "COMPRA STAPLES"
      category: "Job´s"
      sub-category: Supplies
    - keyword: "ALLEGIS GROUP"
      category: ""
      sub-category: ""
    - keyword: "CONTINENTE"
      category: Home
      sub-category: Groceries
    - keyword: "POSTO ABASTECIMENTO"
      category: Car
      sub-category: Fuel
    - keyword: "INTERVALONGO"
      category: Home
      sub-category: Groceries
    - keyword: "FARMACIA"
      category: Daily_Livings
      sub-category: Health
    - keyword: "NETFLIX"
      category: Daily_Livings
      sub-category: Streaming
    - keyword: "LIDL"
      category: Home
      sub-category: Groceries
    - keyword: "GALP"
      category: Car
      sub-category: Fuel
    - keyword: "MERCADONA"
      category: Home
      sub-category: Groceries
    - keyword: "CRV*WELL"
      category: Daily_Livings
      sub-category: Health
    - keyword: "GLOVO"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "CRV*MCD"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "PINGO DOCE"
      category: Home
      sub-category: Groceries
    - keyword: "RESTAURANTE"
      category: Daily_Livings
      sub-category: "Dining Out"
    - keyword: "SUPERMERCADO"
      category: Home
      sub-category: Groceries
    - keyword: "SPOTIFY"
      category: Daily_Livings
      sub-category: Streaming
    - keyword: "VIA VERDE"
      category: Car
      sub-category: Tolls
    - keyword: "COMISSÃO S/"
      category: Bank
      sub-category: Fees
    - keyword: "I.S. COM."
      category: Bank
      sub-category: Fees
    - keyword: "I.SELO"
      category: Bank
      sub-category: Fees
    - keyword: "MAIS CONSIGO"
      category: Bank
      sub-category: Fees
    - keyword: "NOS COM"
      category: Utilities
      sub-category: Phone
    - keyword: "TRF.     0000351 00938121242"
      category: Home
      sub-category: Loan
    - keyword: "POSTO ABASTECIMENT"
      category: Car
      sub-category: Fuel
