server:
  address: 0.0.0.0
  servlet:
    contextPath: /budget
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
    enabled: true

montepio:
  name: Montepio
  firstLine: 10
  dateColumnPosition: 0
  amountColumnPosition: 3
  descriptionColumnPosition: 2
  dateFormat: yyyy-MM-dd
  delimiter: \t

activoBank:
  name: ActivoBank
  firstLine: 10
  dateColumnPosition: 0
  amountColumnPosition: 3
  descriptionColumnPosition: 2
  dateFormat: yyyy-MM-dd
  delimiter: \t

creditoAgricola:
  name: CreditoAgricola
  firstLine: 10
  dateColumnPosition: 0
  amountColumnPosition: 3
  descriptionColumnPosition: 2
  dateFormat: yyyy-MM-dd
  delimiter: \t

cryptoCom:
  name: CryptoCom
  firstLine: 2
  dateColumnPosition: 0
  amountColumnPosition: 3
  descriptionColumnPosition: 1
  dateFormat: "yyyy-MM-dd hh:mm:ss"
  delimiter: ","